import { Roboto } from "next/font/google";
import "./index.scss";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} h-100`}>
      <body className="d-flex flex-column justify-content-between h-100">
        {children}
      </body>
    </html>
  );
}
